apiVersion: apps/v1
kind: Deployment
metadata:
  name: awms-hyperlogic-keycloak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awms-hyperlogic-keycloak
  template:
    metadata:
      labels:
        app: awms-hyperlogic-keycloak
    spec:
      containers:
        - name: awms-hyperlogic-keycloak
          image: ghcr.io/codox/awms-hyperlogic-keycloak:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KEYCLOAK_ADMIN_USER
              value: awms
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: therootpassword
            - name: KEYCLOAK_DATABASE_NAME
              value: keycloak
            - name: KEYCLOAK_DATABASE_HOST
              value: postgres-service
            - name: KEYCLOAK_DATABASE_PORT
              value: "5432"
            - name: KEYCLOAK_DATABASE_USER
              value: awms
            - name: KEYCLOAK_DATABASE_PASSWORD
              value: therootpassword